language: node_js

node_js:
  - 12.13

cache:
  - npm
  - yarn

git:
  depth: false

services:
  - docker

branches:
  only:
    - master
    - develop

jobs:
  include:
    #PULL_REQUEST CHECKING STAGE
    - stage: 'TEST'
      name: 'FRONT TEST'
      if: type = pull_request
      before_install:
        - GIT_DIFF_RESULT=$(eval bash common_job.sh)
        - IS_CHANGED_FRONT=$(echo $GIT_DIFF_RESULT | cut -d ',' -f1)
        - |
          if [ $IS_CHANGED_FRONT != true ]; then 
            exit 0 
          fi
        - cd client
      install:
        - yarn
      script:
        - yarn test

    - name: 'BACK TEST'
      if: type = pull_request
      before_install:
        - GIT_DIFF_RESULT=$(eval bash common_job.sh)
        - IS_CHANGED_BACK=$(echo $GIT_DIFF_RESULT | cut -d ',' -f2)
        - |
          if [ $IS_CHANGED_BACK != true ]; then 
            exit 0 
          fi
        - cd server
      install:
        - yarn
      script:
        - echo 'server test!'

    #DEVELOP SERVER BUILD STAGE
    - stage: 'DEV BUILD'
      name: 'DEV SERVER FRONT BUILD'
      if: branch = develop AND type = push
      before_install:
        - GIT_DIFF_RESULT=$(eval bash common_job.sh)
        - IS_CHANGED_FRONT=$(echo $GIT_DIFF_RESULT | cut -d ',' -f1)
        - |
          if [ $IS_CHANGED_FRONT != true ]; then 
            exit 0 
          fi
        - cd client
      install:
        - yarn
      script:

    - name: 'DEV SERVER BACK BUILD'
      if: branch = develop AND type = push
      before_install:
        - GIT_DIFF_RESULT=$(eval bash common_job.sh)
        - IS_CHANGED_BACK=$(echo $GIT_DIFF_RESULT | cut -d ',' -f2)
        - |
          if [ $IS_CHANGED_BACK != true ]; then 
            exit 0 
          fi
        - cd server
      install:
        - yarn
      script:

    #PRODUCT SERVER BUILD STAGE
    - stage: 'PROD BUILD'
      name: 'PROD SERVER FRONT BUILD'
      if: branch = master AND type = push
      before_install:
        - GIT_DIFF_RESULT=$(eval bash common_job.sh)
        - IS_CHANGED_FRONT=$(echo $GIT_DIFF_RESULT | cut -d ',' -f1)
        - |
          if [ $IS_CHANGED_FRONT != true ]; then 
            exit 0 
          fi
        - cd client
      install:
        - yarn
      script:

    - name: 'PROD SERVER BACK BUILD'
      if: branch = master AND type = push
      before_install:
        - GIT_DIFF_RESULT=$(eval bash common_job.sh)
        - IS_CHANGED_BACK=$(echo $GIT_DIFF_RESULT | cut -d ',' -f2)
        - |
          if [ $IS_CHANGED_BACK != true ]; then 
            exit 0 
          fi
        - cd server
      install:
        - yarn
      script:
