language: node_js

node_js:
  - 12.13

cache:
  - npm
  - yarn

git:
  depth: false

services:
  - docker

branches:
  only:
    - master
    - develop

jobs:
  include:
    #PULL_REQUEST CHECKING STAGE
    - stage: 'TEST'
      name: 'FRONT TEST'
      if: type = pull_request
      script:
        - |
          GIT_DIFF_RESULT=$(echo bash common_job.sh)
          echo $GIT_DIFF_RESULT
          IS_CHANGED_FRONT=$(echo $GIT_DIFF_RESULT | cut -d ',' -f1)
          if [ $IS_CHANGED_FRONT = true ]; then
            echo 'Front test start!'
            cd client
            yarn install
            yarn test
            echo 'test done...'
          else
            echo 'Front is not changed...'
          fi

    - name: 'BACK TEST'
      if: type = pull_request
      script:
        - |
          GIT_DIFF_RESULT=$(echo bash common_job.sh)
          IS_CHANGED_BACK=$(echo $GIT_DIFF_RESULT | cut -d ',' -f2)
          if [ $IS_CHANGED_BACK = true ]; then
            echo 'Back test start!'
            cd server
            yarn install
            echo 'test done...'
          else
            echo 'Back is not changed...'
          fi

    #DEVELOP SERVER BUILD STAGE
    - stage: 'DEV BUILD'
      name: 'DEV SERVER FRONT BUILD'
      if: branch = develop AND type = push
      script:
        - |
          GIT_DIFF_RESULT=$(echo bash common_job.sh)
          IS_CHANGED_FRONT=$(echo $GIT_DIFF_RESULT | cut -d ',' -f1)
          if [ $IS_CHANGED_FRONT = true]; then
            echo 'Develop server front build start!'
            echo 'build done...'
          fi

    - name: 'DEV SERVER BACK BUILD'
      if: branch = develop AND type = push
      script:
        - |
          GIT_DIFF_RESULT=$(echo bash common_job.sh)
          IS_CHANGED_BACK=$(echo $GIT_DIFF_RESULT | cut -d ',' -f2)
          if [ $IS_CHANGED_BACK = "true"]; then
            echo 'Develop server back build start!'
            echo 'build done...'
          fi

    #PRODUCT SERVER BUILD STAGE
    - stage: 'PROD BUILD'
      name: 'PROD SERVER FRONT BUILD'
      if: branch = master AND type = push
      script:
        - |
          GIT_DIFF_RESULT=$(echo bash common_job.sh)
          IS_CHANGED_FRONT=$(echo $GIT_DIFF_RESULT | cut -d ',' -f1)
          if [ $IS_CHANGED_FRONT = true]; then
            echo 'Product server front build start!'
            echo 'build done...'
          fi

    - name: 'PROD SERVER BACK BUILD'
      if: branch = master AND type = push
      script:
        - |
          GIT_DIFF_RESULT=$(echo bash common_job.sh)
          IS_CHANGED_BACK=$(echo $GIT_DIFF_RESULT | cut -d ',' -f2)
          if [ $IS_CHANGED_BACK = true]; then
            echo 'Product server back build start!'
            echo 'build done...'
          fi
